# Generated by Django 6.0.6 on 2026-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_proof',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
    ]
