# Generated by Django 6.0.6 on 2026-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_service_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('HERO', 'Hero Banner'), ('DISCOUNT', 'Discount Poster')], default='HERO', max_length=50),
        ),
    ]
