# Generated by Django 6.0.6 on 2026-07-15 05:27

import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_full_functionality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=services.models.generate_electro_booking_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(choices=[('AC Service', 'AC Service / Repair'), ('Fan Installation', 'Fan Installation / Repair'), ('Wiring', 'Wiring / Rewiring'), ('MCB / Switch', 'MCB / Switch / Socket'), ('Inverter / Battery', 'Inverter / Battery Service'), ('Water Heater', 'Water Heater / Geyser'), ('TV / Home Theatre', 'TV / Home Theatre Setup'), ('Washing Machine', 'Washing Machine Service'), ('Refrigerator', 'Refrigerator Service'), ('Motor / Pump', 'Motor / Water Pump'), ('New Connection', 'New Electrical Connection'), ('Other', 'Other Electrical Work')], max_length=100)),
                ('appliance_brand', models.CharField(blank=True, help_text='e.g., Samsung, LG, Voltas', max_length=100)),
                ('issue_description', models.TextField(help_text='Describe the problem')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('Morning (8AM–12PM)', 'Morning (8AM–12PM)'), ('Afternoon (12PM–4PM)', 'Afternoon (12PM–4PM)'), ('Evening (4PM–8PM)', 'Evening (4PM–8PM)')], default='Morning (8AM–12PM)', max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Technician Assigned', 'Technician Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('technician_name', models.CharField(blank=True, max_length=200)),
                ('technician_phone', models.CharField(blank=True, max_length=30)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electro_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electro Booking',
                'verbose_name_plural': 'Electro Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
